### PR TITLE
Update to support / match latest esp-idf

### LINKED ISSUE #4: VSPICLK_OUT_MUX_IDX was removed
hi

since last esp-idf update there was a remove/change 

https://github.com/espressif/esp-idf/commit/23455de4c2f6f8308f60d11badf4a95ed644bd57#diff-da26bb48d6c7dd629da1e755d7283f29L138

only for info:
if we add in  components/esp32/include/soc/gpio_sig_map.h
`#define VSPICLK_OUT_MUX_IDX			63`

then compile is ok, 
other side

...... /components/nofrendo-esp32/spi_lcd.c:263:34: error: 'VSPICLK_OUT_MUX_IDX' undeclared (first use in this function)
     gpio_matrix_out(PIN_NUM_CLK, VSPICLK_OUT_MUX_IDX,0,0);

https://github.com/espressif/esp32-nesemu/blob/master/components/nofrendo-esp32/spi_lcd.c#L253

best wishes
rudi ;-)

### PR DESCRIPTION
**Pull request by mattkelly**
Tested against esp-idf v2.0-rc1.

The actual issue preventing the build from working with v2.0-rc1 is `VSPICLK_OUT_MUX_IDX` being renamed to `VSPICLK_OUT_IDX`, which is fixed here. The other changes eliminate warnings introduced by the update.

Fixes #4.

### CODE REVIEW

**Comment by rpasek** [comment]
Nice 1!
